name: Jail-Plugin
description: Plugin to make a simple, but useful jail.
website: nani.games.net
author: Exenco
version: 1.0
api-version: 1.13
main: net.exenco.core.JailPlugin

commands:
  jail:
    description: Set locations for the jail.
    permission: jail.set

permissions:
  jail.set:
    description: Permission for Jailcommand
    default: op
  jail.override.break:
    description: Lets the player break any blocks in jail.
    default: op
  jail.override.place:
    description: Lets the player place any blocks in jail.
    default: op
  jail.override.execute:
    description: Lets the player execute any commands in jail.
    default: op